name: cd
on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.25.1"

            - name: Build application
              run: go run scripts/build.sh

            - name: Deploy application
              run: echo "Deploying application..." # Replace with actual deployment commands